@echo off
cd /d "c:\xampp\htdocs\pos-final"
echo Setting Git config...
git config user.name "Kerry"
git config user.email "kerry@example.com"
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit of POS system"
echo Renaming branch...
git branch -M main
echo Pushing to GitHub...
git push -u origin main
